### ISSUE TITLE
documentation: clarify the use of *.local.js and *.local.json config files

### ISSUE THREAD

**Issue by greaterweb** [strongloop/loopback-boot#101]
Currently the use of `*.local.{js,json}` config files are loosely documented within the [environment specific configuration](http://docs.strongloop.com/display/public/LB/Environment-specific+configuration) page, their intended role is a little unclear though and behavior may produce unexpected results a developer. Inclusion on this documentation page leads you to believe `local` is an environment (eg `NODE_ENV=local`, but it's behavior differs from other `env` specific config files.

From my experience, it seemed that if I had three files `config.json`, `config.local.json` and `config.development.json` if I started my server with `NODE_ENV=development` the file `config.local.json` would not factor into the final configuration. This is not the case as `config.local.json` is [always factored](https://github.com/strongloop/loopback-boot/blob/master/lib/config-loader.js#L84-L88).

As the `*.local.{js,json}` config is always loaded, it is unclear what role it serves compared to the root config. Specifically, if both `config.json` and `config.local.json` are always loaded it's unclear why they are both needed.

Consider the following:

`config.json`
```json
{
   "foo": "bar"
}
```

`config.local.json`
```json
{
   "foo": "baz",
   "isLocal": true
}
```

`config.production.json`
```json
{
   "foo": "bat"
}
```

Running the app with `NODE_ENV=production` produces a merged config which looks like this:
```json
{
   "isLocal": true,
   "foo": "bat"
}
```

This is applicable to all types of configs loaded using [`findConfigFiles`](https://github.com/strongloop/loopback-boot/blob/master/lib/config-loader.js#L80-L100) function.

Related: #93

**Comment by greaterweb** [comment]
Looking at the usage in [this example](https://github.com/strongloop/loopback-example-full-stack/tree/20c60b4beb76e4805b21f28353b6d9867236e8ba/server) it appears that `config.local.js` may be intended to polyfil the fact you can't have a `config.js` file. If this is indeed the intended usage, the `.local` certainly confuses things a bit.

**Comment by sgilligan** [comment]
+1

**Comment by AndreGeng** [comment]
+1

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
@greaterweb You are correct that `config.local.js/json` is always loaded (if it exists).  
I will try to clarify this in the docs.

I can't authoritatively speak to the intent of the design, as I just write the docs, but I believe you're basically right that `config.local.js` exists to be able to perform programmatic actions instead of simply setting primitive values as you can do in a JSON file.

Also, I thought the docs were clear that these are _additive_ to the existing `config.json` file; that is, they are there to **override** the original/default values set there. Again, I'll try to clarify.

@bajtos might be able to comment on the intent of the design.

**Comment by bajtos** [comment]
The original idea was to use `*.local.js*` files for machine-local configuration that is never committed to version control system (git). Over the time, the `local` files become a workaround for the fact you can't have a config.js file as @greaterweb wrote.

I agree this situation is rather confusing. I don't know yet what is the best solution, whether an incremental improvement will be sufficient (e.g. #80) or whether we need to redesign the whole convention for loading and merging different config sources.

**Comment by crandmck** [comment]
@bajtos @greaterweb I updated https://docs.strongloop.com/display/LB/Environment-specific+configuration to try to clarify the situation.  I would appreciate it if you would take a look and let me know if I missed anything or got something wrong, or if it's still not clear.  Thanks.

**Comment by bajtos** [comment]
@crandmck thank you for the update, I have added few more config files to the list.

The file loading follows few simple rules. We have different configuration types - config, datasources, model-config, middleware, component-config. For each config type, we load the following files:
 - {type}.json - always, and only JSON
 - {type}.local.json/js - always if exists, either JSON or JS
 - {type}.{env}.json/js - always if exists, either JSON or JS, env is "development" by default

**Comment by crandmck** [comment]
Thanks for updating the docs.  I'm going to close this now, since I think we've addressed it.

**Comment by danielrvt** [comment]
If we want to use the merged configuration in our code, how can we get a hold on it?

I'm currently trying: `require('../config');` and it seems to always load `config.json` (not `config.local.js`)

**Comment by dancingshell** [comment]
@danielrvt what are you trying to accomplish? If you just need to get values out of the config you can:

```js
var app = require('server.js');
var yourConfigValue = app.get('key-to-retreive-from-config');
```
