### ISSUE TITLE
Command line browserify loopback-boot

### ISSUE THREAD

**Issue by BerkeleyTrue** [strongloop/loopback-boot#108]
We compile on npm prepublish for production. When trying to browserify the loopback script we have does not get run.

Not exactly sure how to add boot instructions from command line. I would form a PR but this isn't something I am familiar with. 

Is there someway to easily accomplish this?

**Comment by ritch** [comment]
> When trying to browserify the loopback script we have does not get run.

Is this referring to a `boot()` script?

**Comment by BerkeleyTrue** [comment]
Referring to boot.compileToBrowserify.

**Comment by bajtos** [comment]
@BerkeleyTrue I am not sure if I am understanding you correctly. Are you asking us to provide a command-line tool for creating a browserify bundle for a given LoopBack application?

Check out [loopback-example-offline-sync/client/lbclient/build.js](https://github.com/strongloop/loopback-example-offline-sync/blob/4b0f60bf716bbcb04b985e86eb443eaa3f7fc420/client/lbclient/build.js), it provides a method that we call from [Gruntfile](https://github.com/strongloop/loopback-example-offline-sync/blob/4b0f60bf716bbcb04b985e86eb443eaa3f7fc420/Gruntfile.js#L389-L392).

It should be pretty easy to modify the script to work as a CLI tool.

**Comment by bajtos** [comment]
I am closing this issue since there was not activity in more than a year.
