### ISSUE TITLE
Unable to boot in the browser - Number.isFinite is not a function.

### ISSUE THREAD

**Issue by mrfelton** [strongloop/loopback-boot#123]
The change at https://github.com/strongloop/loopback-boot/commit/044a4df07a8c076ec0c72e98261fdb44631f7acd#diff-3a73542dc68d28ea0d34b33d6df62f85R119 breaks when run in the browser via browserify.

When I'm running unit tests in PhantomJS using karma I get the following fatal error:

"TypeError: 'undefined' is not a function (evaluating 'Number.isFinite(parseInt(v, 10))')
at /devenv/build/client/lbclient/browser.bundle.js:1282"

Number.isFinite is not well supported in browsers.

**Comment by mrfelton** [comment]
Patch above updates to use the polyfill code detailed on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite in place of Number.isFinite()

**Comment by raymondfeng** [comment]
@mrfelton Can you submit your patch as a github pull request?

**Comment by Amir-61** [comment]
[PR#126](https://github.com/strongloop/loopback-boot/pull/126) fixes the issue. closing the ticket now.

Thanks
