### ISSUE TITLE
mixinDirs vs. mixinSources

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-boot#137]
Now that we have the `mixinDirs`, I believe there is no reason to keep `mixinSources` around. For example: https://github.com/strongloop/loopback-boot/blob/ac5265f726748a0f324c1a218a04d39e241f2b3b/lib/compiler.js#L88

@bajtos thoughts?

**Comment by bajtos** [comment]
IMO, mixinSources are crucial to keep the size of the browserified client as small as possible and leave out any mixins that are not used by client models. If I wanted to simplify the bootloader, then I would remove `mixinDirs` option instead.

**Comment by bajtos** [comment]
> mixinDirs vs. mixinSources

Let me explain the difference between these two options. All files in `mixinDirs` are always loaded and the mixins are registered with loopback runtime. OTOH, only those files that referenced by an application model are loaded from `mixinSources`. The option `mixinSources` mirrors the behaviour of `modelSources`.

**Comment by fabien** [comment]
Hi @bajtos, thanks for the exmplanation. Is it then on purpose that `mixinSources` is not referenced as an option in `index.js`?

**Comment by bajtos** [comment]
>  Is it then on purpose that mixinSources is not referenced as an option in index.js?

Oh, that would be an oversight.

**Comment by bajtos** [comment]
@fabien see #139

**Comment by bajtos** [comment]
Fixed by #139.
