### ISSUE TITLE
mergeObjects could not handling null property

### ISSUE THREAD

**Issue by kidwm** [strongloop/loopback-boot#157]
server/datasources.json
```json
"sqlite3": {
    "name": "sqlite3",
    "connector": "loopback-connector-sqlite",
    "file_name": null,
    "debug": false
  }
```
server/datasources.production.json
```json
"sqlite3": {
    "name": "sqlite3",
    "connector": "loopback-connector-sqlite",
    "file_name": "./database.sqlite3",
    "debug": false
  }
```
Error:
```
node_modules/loopback-boot/lib/config-loader.js:253
  var origValue = target[key];
                        ^

TypeError: Cannot read property '0' of null
```

**Comment by superkhau** [comment]
Can you provide a link to a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by kidwm** [comment]
@superkhau here it is:
https://github.com/kidwm/loopback-sandbox

**Comment by superkhau** [comment]
@kidwm Verified. Escalating to bug.

**Comment by superkhau** [comment]
@kidwm Actually, can you try changing the key `file_name` to `file`. I don't believe we support `file_name`.

**Comment by kidwm** [comment]
@superkhau loopback-connector-sqlite use this config property and works fine.

Change to `file` did not make any deference.

**Comment by superkhau** [comment]
>loopback-connector-sqlite use this config property and works fine.

What do you mean? The connector only supports the property `file` and not `file_name`. I cloned your repo, changed `datasources.local.json`'s `file_name` property to `file` and the error disappears. Can you try this?

**Comment by superkhau** [comment]
Another question, why are you using `file_name` at all? Is this documented somewhere?

**Comment by kidwm** [comment]
@superkhau You maybe forgot to also change the property in `datasources.json`.

https://github.com/Synerzip/loopback-connector-sqlite

**Comment by superkhau** [comment]
@kidwm I see, we're looking at different repos. I'm looking at our officially supported connector: https://github.com/strongloop/loopback-connector-sqlite3

You're going to have to ask `Synerzip` about his connector not working for you instead of here. Closing.

**Comment by kidwm** [comment]
@superkhau Thanks for the info that you guys finally has official sqlite3 support.

If you still care about this issue, I've made another commit to remove sqlite3 config.

**Comment by superkhau** [comment]
@kidwm No problem. Let me know if you are still running into issues.
