### ISSUE TITLE
dataSources error on boot aren't handle?

### ISSUE THREAD

**Issue by Elindorath** [strongloop/loopback-boot#161]
Hi there,

As I was digging around boot error handling, I was surprised to find out that a mispelled hostname in datasources.json does fire an error, but not the way I expected:

```
Connection fails:  { [Error: getaddrinfo ENOTFOUND postgres postgres:5432]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'postgres',
  host: 'postgres',
  port: 5432 }
It will be retried for the next request.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND postgres postgres:5432
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```

An error like this doesn't prevent the app from booting, doesn't give an error to the boot callback, and is not handle with a listener on app error.

The only way I found to handle this was to listen on all datasources error in boot callback, like this:

```javascript
// Bootstrap the application, configure models, datasources and middleware.
// Sub-apps like REST API are mounted via boot scripts.
boot(app, __dirname, function(err) {
  if (err) throw err;

   // Here is how I handle dataSources errors
  Object.keys(app.dataSources).map(function handleDataSourcesError(name) {
    app.dataSources[name].on('error', function noop() {});
  });

  // start the server if `$ node server.js`
  if (require.main === module) {
    app.start();
  }
});
```

Is that intended? And if it does, explanations are more than welcome.

Versions:

```
node v4.2.1
npm v3.3.10
strongloop v5.0.1
loopback v2.22.0
loopback-boot v2.6.5
loopback-component-explorer v2.1.0
loopback-connector-postgresql v2.4.0
loopback-datasource-juggler v2.39.0
```

**Comment by Amir-61** [comment]
@Elindorath  
>An error like this ..., doesn't give an error to the boot callback
We tried to reproduce this issue and we could not reproduce it; could you please share a repo.

Note: Probably you are not passing the error in your bootscript callback and that's why you cannot catch the error in the boot callback! But to make sure we need to see your code and we can comment on it!

My suggestion would be reproduce the issue using loopback-sandbox (Please see: https://github.com/strongloop/loopback-sandbox) and share it with us, if you cannot share the whole project in public.

Thanks!

**Comment by jannyHou** [comment]
Hey @Elindorath If you still have questions about boot related issues, please provide your code (you can fork this repo https://github.com/strongloop/loopback-sandbox and upload your project to sandbox) then let's solve problems together!
For future reference, please ask questions on [google group](https://groups.google.com/forum/#!forum/loopbackjs)
