### ISSUE TITLE
Environment specific files merge with arrays doesn't merge properly.

### ISSUE THREAD

**Issue by RameshChoudhary** [strongloop/loopback-boot#172]
Trying to use some dev specific models for dev env so defined files are

model-config.json

``` javascript
{
    "_meta": {
        "sources": [
            "loopback/common/models",
            "loopback/server/models",
            "../common/models"
        ],
        "mixins": [
            "loopback/common/mixins",
            "loopback/server/mixins"
        ]
    },
   "model1": {
    "dataSource": "db",
    "public": true
  },
...
}
```

model-config.dev.json

``` javascript
{
    "_meta": {
        "sources": [
            "loopback/common/models",
            "loopback/server/models",
            "../common/models",
            "../devmodels/models"
        ],
        "mixins": [
            "loopback/common/mixins",
            "loopback/server/mixins"
        ]
    },
   "devmodel1": {
    "dataSource": "db",
    "public": true
  },
...
}
```

Now when we start the application it throws eror
`Cannot merge array values of different length for the option _meta`

In loopback-boot/config-loader.js this function compares for length of arrays and throws the error

``` javascript
function mergeArrays(target, config, keyPrefix) {
  if (target.length !== config.length) {
    return 'Cannot merge array values of different length' +
      ' for the option ' + keyPrefix + '.';
  }
...
}
```

Want to know the reason why instead of merging content of both arrays ,it is comparing length and if they are of same length then overriding content of target file  with config file and if not of same length then throws  error and why this is not handled. 

## Acceptance criteria

- [ ] Fix the algorithm used to merge array values to better understand the structure of `model-config.json` file and use a specialized algorithm for `_meta.sources` and `_meta.mixins`. These two array values should be replaced in whole (e.g. `_meta.mixins` provided by `model-config.dev.json` should replace the `_meta.mixins` value provided by `model-config.json`).

- [ ] To avoid a breaking change, we need to introduce a feature flag (a new `boot()` option) allowing apps to opt-in or opt-out of the new merge algorithm.

**Comment by jbcpollak** [comment]
I ran into a similar probably trying to add external models to via model-config.local.js.

in model-config.json I have:

```
{
  "_meta": {
    "sources": [
      "loopback/common/models",
      "loopback/server/models",
      "../common/models",
      "./models"
    ],
   ....
}
```

And in model-config.local.js I have this:

```
'use strict';

let log = require('lib/logger')('modelConfig');

let externalModels = require('external_models');

module.exports = {
	"_meta": {
		"sources": [
			externalModels
		]
	},
        ....
};
```

I get this error when I try and run loopback:

```
Error: Cannot apply .../server/model-config.local.js: Cannot merge array values of different length for the option `_meta.sources`.
    at mergeModelConfig (.../node_modules/loopback-boot/lib/config-loader.js:157:11)
    at mergeConfigurations (.../node_modules/loopback-boot/lib/config-loader.js:142:5)
    at loadNamed (.../node_modules/loopback-boot/lib/config-loader.js:76:16)
    at Object.ConfigLoader.loadModels (.../node_modules/loopback-boot/lib/config-loader.js:36:10)
    at compile (.../node_modules/loopback-boot/lib/compiler.js:42:18)
    at bootLoopBackApp (.../node_modules/loopback-boot/index.js:139:22)
    at Object.<anonymous> (.../server/server.js:24:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
```

Is there a workaround? Is it possible to manually access and merge the _meta.sources object through the app?

**Comment by f-w** [comment]
I am using loopback-boot@2.23.0 and still got this error. Is the fix available on any published release?

**Comment by AlexOwen** [comment]
This still exists in loopback-boot@2.27.1

**Comment by andrewwiik** [comment]
Still exists in 3.1.1

**Comment by luxigo** [comment]
this is still an issue...

**Comment by juanvillegas** [comment]
Still an issue in LB 3 today...

**Comment by vishwas-verma-sib** [comment]
This is still an issue with loopback.
