### ISSUE TITLE
Cannot resolve path "cors" in loopback sdk angular

### ISSUE THREAD

**Issue by kennethlynne** [strongloop/loopback-boot#179]
https://github.com/strongloop/loopback-sdk-angular/issues/216 

Probably related to the latest changes in this repo

**Comment by GonzaGonza** [comment]
+1

**Comment by Amir-61** [comment]
@kennethlynne,

Did @GonzaGonza solve your problem? Can we close this ticket now? Or you still have the same problem? If so please provide a sample repo using our [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) reproducing the issue and we will look into it.

Thanks!

**Comment by kennethlynne** [comment]
Yes, thanks

**Comment by Amir-61** [comment]
Thanks that the problem is solved :-)
