### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by LoicMahieu** [strongloop/loopback-boot#182]
Since #177 my application throws the error:
```
TypeError: Cannot convert undefined or null to object
/app/api/node_modules/loopback-boot/lib/executor.js in null.<anonymous> at line 403
```

It is because I parse myself env variables for datasource config. The results of the parsing may contains `null` values but:
```js
typeof null === 'object'
```
And so:
```js
Object.keys(null)
```
throws: **TypeError: Cannot convert undefined or null to object**

The `null` values were things like `port` etc...
I updated my application for giving default port and so avoid null value but it should certainly be fixed.

**Comment by davidcheung** [comment]
Thanks @LoicMahieu!
I can reproduce this, definitely an oversight during implementation

**Comment by davidcheung** [comment]
this is major because 
```js
{
  "db": {
    "host": "localhost",
    "port": null, //this will fail
    "database": "database",
    "name": "db",
    "connector": "mongodb"
  }
}
```
