### ISSUE TITLE
Latest version of lodash 

### ISSUE THREAD

**Issue by pmoelgaard** [strongloop/loopback-boot#186]
Any plans to update the dependencies to latest version, especially lodash, so it would not be necessary to install dependencies locally for this module ?

**Comment by Amir-61** [comment]
Hi @pmoelgaard,

There is no plan at least at the moment to update `lodash` dependency... Please ask this kind of questions in out [Google group](https://groups.google.com/forum/#!forum/loopbackjs). We prefer to have the issue section of Github for bug reporting and feature requests. Thanks for your cooperation :-) I will be closing this ticket now.

Thanks!

**Comment by pmoelgaard** [comment]
@Amir-61 Thanks for the response, and thanks for the heads up on the Google group.
