### ISSUE TITLE
Order of setting host and port variables in executor.js (Causes problem in AWS Elastic Beanstalk)

### ISSUE THREAD

**Issue by ahmetcetin** [strongloop/loopback-boot#189]
App server in AWS Elastic Beanstalk set HOST env variable to public api of the EC2. Nginx running on the machine uses this ip together with PORT env variable (for reverse proxy). So, instead of using HOST variable, I take care of this in config.local.js to query NODE_ENV and setting host property accordingly. Problem is, in the following code of executor.js:

``` node
function setHost(app, instructions) {
  // jscs:disable requireCamelCaseOrUpperCaseIdentifiers
  var host =
    process.env.npm_config_host ||
    process.env.OPENSHIFT_SLS_IP ||
    process.env.OPENSHIFT_NODEJS_IP ||
    process.env.HOST ||
    process.env.VCAP_APP_HOST ||
    instructions.config.host ||
    process.env.npm_package_config_host ||
    app.get('host');

  if (host !== undefined) {
    assert(typeof host === 'string', 'app.host must be a string');
    app.set('host', host);
  }
}
```

host variable I set in config.local.js is overwritten by the env variables set in the machine, which obviously a problem in AWS Beanstalk, as it produces address to be used for express as public ip/port vars which is in use by Nginx, and it results EADDRSINUSE error.

My thinking is, if I exclusively set the host/port settings in config.local.js, why loopback-boot overwrites these values? I believe it's developer's responsibility to take care of the settings depending on the environment, not loopback-boot's. That's why there are config.local.js, config.{env}.js (json) files. To overcome the problem, I set npm_config_host env variable in EC2 to localhost, so that it overwrites HOST variable, but I believe that shouldn't be this way. The priority should be what developer sets in his/her settings in config files.

**Comment by geruiz** [comment]
Hi, I have the same problem.  The environment value of HOST override my configuration, though the documentation didn't say so.

**Comment by ahmetcetin** [comment]
yeah, but it's easy to overcome in fact, just define a new env variable on your beanstalk/ec2/or whatever the virtual machine is, as "npm_config_host" and set it to localhost, it works.

**Comment by geruiz** [comment]
I already resolve it (I clear the "host" env variable).  But I think this should appear on the documentation page (precedence of the env variables over the configuration value).

**Comment by ahmetcetin** [comment]
totally agree.

On Wed, May 25, 2016 at 2:23 PM geruiz <notifications@github.com> wrote:

> I already resolve it (I clear the "host" env variable). But I think this
> should appear on the documentation page (precedence of the env variables
> over the configuration value).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/loopback-boot/issues/189#issuecomment-221558102>
>
-- 
Ahmet Cetin

**Comment by richardpringle** [comment]
@ahmetcetin, so just to clarify, you did find a workaround?

What do you think, should we just update the documentation or should this be changed so that the variable is easier to override?... or both

**Comment by ahmetcetin** [comment]
I think it would nice to add some note in documentation for future reference for other users.

**Comment by agokhale** [comment]
a explicit user setting is being silently overridden in every case on a unix like system.  setting a mostly undocumented environment var  is not a good workaround for this POLA damage. 
 Simply reordering the fallthrough  stack would probably be enough.. if this had a maintainer.
