### ISSUE TITLE
disable boot scripts

### ISSUE THREAD

**Issue by falcondai** [strongloop/loopback-boot#191]
I wish there is a way (via `options` to `boot()`) to disable the behavior of executing everything in `boot/`: https://github.com/strongloop/loopback-boot/blob/master/lib/compiler.js#L66

My reason is that i wanted to reuse model definitions in a worker process (that communicates with the web app process via a push-pull work queue, and directly with the database). After much research, i implemented my solution by hiding the web app's boot scripts under `boot/app` so i can call `boot(app)` in my worker process. But i think it would be more elegant if developers can disable the default behavior.

**Comment by superkhau** [comment]
There is work being done on loopback-boot refactoring ATM. See https://github.com/strongloop/loopback-boot/pull/181. Thanks for the input! Feel free to comment in that PR if you have any more suggestions.

We should take this into consideration @raymondfeng.
