### ISSUE TITLE
existsSync is deprecated; maybe use statSync in a try catch instead

### ISSUE THREAD

**Issue by jskrzypek** [strongloop/loopback-boot#201]
Instead of 

``` js
fs.existsSync('some/file');
```

this probably ought to be a wrapper around `fs.statSync`

``` js
fileExistsSync('some/file');
// ...
function fileExistsSync(path) {
    try {
        fs.statSync('some/file');
        return true;
    } catch (e) {
        return false;
    }
}
```

**Comment by superkhau** [comment]
Would you like to submit a PR instead? Keep in mind we still support Node 0.10 (which has statSync available https://nodejs.org/docs/v0.10.0/api/fs.html#fs_fs_statsync_path).

**Comment by jskrzypek** [comment]
Happy to, I'll submit one tomorrow.

**Comment by jskrzypek** [comment]
@superkhau PR submitted. I tried to make it as minimal as possible.

**Comment by bajtos** [comment]
The deprecation of `fs.existsSync` was reverted - see e.g. https://nodejs.org/dist/latest-v6.x/docs/api/fs.html#fs_fs_existssync_path and https://nodejs.org/api/fs.html#fs_fs_existssync_path

I am closing this issue as no longer relevant.
