### ISSUE TITLE
Suggestion: calling the initialize code of the base model when initializing a model

### ISSUE THREAD

**Issue by fs523577192** [strongloop/loopback-boot#212]
I have defined some models inheriting from a model called StatusModel. I want to disable the delete method of all StatusModel so I write the following in status-model.js:

```
module.exports = function (Statusmodel) {
    Statusmodel.disableRemoteMethod("deleteById", true);`
}
```

However in the explorer I can still see DELETE method on those models inheriting from StatusModel.

I search for the code calling the initialization function of a model and in [HERE](https://github.com/strongloop/loopback-boot/blob/master/lib/executor.js#L250) I find that loopback-boot does not call the initialization function of the base model of a model.

I think it is reasonable to call the initialization function of the base model when a model is being initialized. At least, when the JS file of a inheriting model is generated, the code calling the initialization function of the base model should be added automatically.

**Comment by davidcheung** [comment]
Hi @fs523577192, thanks for your suggestion.
we have had run into issues in similar scenarios ( if i understood the issue you described correctly )

I think this is more of an issue of the model-builder, perhaps somewhere in the `extend()` function https://github.com/strongloop/loopback-datasource-juggler/blob/baa557116c4bf7b381fdb40e6c4eaef131909594/lib/model-builder.js#L355 where it can't cover all the use cases.

a solution could be to do something like the following comment: 
https://github.com/strongloop/loopback/issues/1485#issuecomment-163711525
