### ISSUE TITLE
Document refactored design of loopback-boot

### ISSUE THREAD

**Issue by davidcheung** [strongloop/loopback-boot#230]
>I think it would be worthwhile to describe the new features in 3.0-RELEASE-NOTES too (the modular design and how to build 3rd party boot plugins). In my experience, the process of writing the documentation usually discover missing pieces and/or rough edges. 

- [ ] describe new design 
- [ ] describe new feature
- [ ] example/tutorial/blogpost on how to build your boot-plugin 

related to #181

**Comment by bajtos** [comment]
Our focus is on LB4+ now.
