### ISSUE TITLE
2.0 throws that model-config.json is using 1.x format; where is the 2.x format?

### ISSUE THREAD

**Issue by STRML** [strongloop/loopback-boot#27]
`compiler` [asserts](https://github.com/strongloop/loopback-boot/blob/6bf995c55b41789886f973428317c1871903dca0/lib/compiler.js#L79) that model configuration objects don't have `properties`, `base`, or `plural` configurations, but the [docs](http://docs.strongloop.com/display/LB/Model+definition+reference) show configuration showing these properties.

What properties am I supposed to use?

**Comment by ORESoftware** [comment]
I am having this issue, is there simply a way to explicitly pass model-config.json to 

`boot(app, {})`?

Something like:

`boot(app, {
   modelConfig: require('some-custom-file.json')
})`

**Comment by ORESoftware** [comment]
Also, just an aside, in the boot documentation, it's not clear to me what the difference is between model configuration and model definitions:

```
[models]	Object	
Object containing Model configurations.
[modelDefinitions]	Array	
List of model definitions to use. When options.modelDefinitions is provided, loopback-boot does not search filesystem and use only the models provided in this argument.
```

anybody care to explain? thanks!

**Comment by crandmck** [comment]
@davidcheung @deepakrkris ^

**Comment by bajtos** [comment]
> what the difference is between model configuration and model definitions

In short: model configuration is the data in `server/model-config.json`, model definition is the data from `common/models/{name}.json` (see also https://github.com/strongloop/loopback-boot/issues/27#issuecomment-49976544)
