### ISSUE TITLE
isomorphic and uglify causing "AssertionError: must provide a valid {{SharedClass}}"

### ISSUE THREAD

**Issue by doowb** [strongloop/loopback-boot#273]
# Description/Steps to reproduce

I'm following the isomorphic example and browserifying the code. This results in a bundle that's >1MB so I thought I would try using uglify to minify the code.

I was able to minify the code and reduce the bundle to 600KB, but now I receive the above error.
Stepping through the code, I see that the there's a line asserting that when this code is checked: `sharedClass.constructor.name === 'SharedClass'`, the constructor name is `'n'` because of the minification.

Are there any options built into `loopback-boot` that can handle minification? If not, is there another option to generate a browser client from an existing loopback api? I guess this would be similar to how the `explorer` generates a client for the rest api?

**Comment by bajtos** [comment]
Sorry for the long silence on our side. In October 2018 (last month), LoopBack 4 GA was released and LoopBack 3.x entered LTS mode where new features and potentially disruptive changes are no longer accepted. I would be very reluctant to make changes in LoopBack just to support (advanced) minification of browserified code.

Having said that: the problematic line you shown above is coming from strong-remoting.

See https://github.com/strongloop/strong-remoting/blob/e10c5345402a4066ac9614b412276a3b2a8ed212/lib/remote-objects.js#L229-L233
```js
RemoteObjects.prototype.addClass = function(sharedClass) {
  assert(sharedClass && sharedClass.constructor.name === 'SharedClass',
    g.f('must provide a valid {{SharedClass}}'));
  this._classes[sharedClass.name] = sharedClass;
};
```

You can try to monkey-patch that method in your application to remove the class-name check.

Something along the following lines may work. I don't have bandwidth to try it myself, sorry for that.

```js
const app = loopback();
app.remotes().prototype.addClass = function(sharedClass) {
  this._classes[sharedClass.name] = sharedClass;
};
// boot the app, etc.
```
