### ISSUE TITLE
Why next() requires to trigger process.nextTick in bootscript.

### ISSUE THREAD

**Issue by rahulrkr08** [strongloop/loopback-boot#276]
I want to do DB operation after User login, for that I have written boot script. Please check below code,

```
module.exports = function(app, cb) {

  app.models.User.afterRemote('login', function (ctx, user, next) {
    console.log(ctx.result);
    next()
  });
  process.nextTick(cb); // Remove if you pass `cb` to an async function yourself
};
```
But when I am removing next() function from afterRemote callback, the application gets hold on afterRemote function. I don't want to process should wait to complete my DB process. process.nextTick not triggers for this asynchronous events. Can anyone help me to understand why we need next() function in remote to trigger `process.nextTick(cb);`

**Comment by bajtos** [comment]
@rahulrkr08 is this issue still relevant?

I think you are confusing two unrelated concepts:

(1) A boot script can be optionally asynchronous. If the function exported by a boot script accepts a `cb` argument, then it must call this callback to signal when the async work has finished. In your case, the boot script can be simplified to a synchronous version.

```js
module.exports = function(app) {
  app.models.User.afterRemote('login', function (ctx, user, next) {
    console.log(ctx.result);
    next()
  });
};
```

(2) Remoting hooks are always callback-based, we don't support synchronous hook handlers. If you don't call `next` from your hook, then LoopBack assumes the hook handler is still doing work and thus waits forever.

If you want to run your "after login" task in the background, then simply don't wait for your background task to finish and call `next()` right away. If you do so, then it's the responsibility of the background task to handle any errors it may encounter.

```js
module.exports = function(app, cb) {
  app.models.User.afterRemote('login', startBackgroundTaskAfterLogin);
}

function startBackgroundTaskAfterLogin(ctx, user, next) {
    // start the background task
    doStuffAfterLogin(ctx.result, function(err) {
      if (err) {
        // you are on your own when an error happens
        // the error MUST NOT be passed to next because 
        // next was already called.
        console.error('doStuffAfterLogin failed', err);
      }
    });

    // let the original request-handling flow continue
    next();
  });

function doStuffAfterLogin(result, cb) {
  // do some stuff
  process.nextTick(cb);
}
```
