### ISSUE TITLE
Expected value of app.get('env')

### ISSUE THREAD

**Issue by greaterweb** [strongloop/loopback-boot#28]
When initializing `boot` with `options`, if `options.env` is supplied, that value does not match what `app.get('env')` returns.

The [`env` variable](https://github.com/strongloop/loopback-boot/blob/master/lib/compiler.js#L29) is set based on options provided and passed to config loader methods for app, models and datasources. It is never stored beyond the compiler and config loader initialization.

In my opinion it would be beneficial to have `app.get('env')` match what is supplied in `options.env`.

**Comment by bajtos** [comment]
+1

We should consider modifying the code building the `env` variable to take into account the current value of `app.get('env')` too.

**Comment by bajtos** [comment]
Fixed by #164.

**Comment by greaterweb** [comment]
:+1: I'll be sure to check it out
