### ISSUE TITLE
export-api-def doesn't work with loopback-boot@3

### ISSUE THREAD

**Issue by amenadiel** [strongloop/loopback-boot#291]
# Description/Steps to reproduce

Use the generator to scaffold a new application. Then export the api definition:

```sh
npm i -g loopback-cli
lb app experiment
cd experiment
lb export-api-def
```
![paso2](https://user-images.githubusercontent.com/238439/57945074-e138a180-78a6-11e9-86e4-886c65d83ad0.png)

It works! At this point, the dependencies list `loopback-boot@2.6.5`

If you upgrade to loopback-boot@3, like it's shown in [loopback-getting-started](https://github.com/strongloop/loopback-getting-started/blob/f56e9a10103848fdfc718c542591d75a539dd950/package.json#L18)

Running `lb export-api-def` yields an empty definition:

![Captura de pantalla_2019-05-17_13-27-17](https://user-images.githubusercontent.com/238439/57945350-aa16c000-78a7-11e9-9273-1d7891ef40a3.png)

# Link to reproduction sandbox

Uh... should I provide access to my linux environment? :question: 

# Expected result

It should export at least the same information than before. I was hoping for it to actually output more info. 

# Additional information

```sh
$  node -e 'console.log(process.platform, process.arch, process.versions.node)'

linux x64 8.16.0
```

**Before:**
```sh
$  npm ls --prod --depth 0 | grep loopback

├── loopback@3.25.1
├── loopback-boot@2.28.0
├── loopback-component-explorer@6.4.0
```

**After:**
```sh
$  npm ls --prod --depth 0 | grep loopback

├── loopback@3.25.1
├── loopback-boot@3.3.0
├── loopback-component-explorer@6.4.0

```

**Comment by mrbatista** [comment]
@amenadiel I have open PR strongloop/generator-loopback#411 to resolve this issue.
