### ISSUE TITLE
Loopback-boot updating to 3.3.1 producting "LoopBack server listening @ https://undefined:undefined/"

### ISSUE THREAD

**Issue by ashish991** [strongloop/loopback-boot#307]
After updating loopback boot to 3.3.1 which is latest and stable version. Unable to start the lb3 server using cmd "node ."
Getting info "**LoopBack server listening @ https://undefined:undefined/**" . It doesn't allow to browse the explorer and even call the api's.

**Comment by dhmlau** [comment]
@ashish991, what's the latest version that works for you? 
From the [change log](https://github.com/strongloop/loopback-boot/blob/master/CHANGES.md#2019-06-24-version-331), 3.3.1 only contains non-code related changes. Thanks.
