### ISSUE TITLE
`views` dir not found properly

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-boot#39]
`views` directory not being set properly with 2.x layout.

For example, in [loopback-example-relation](https://github.com/strongloop/loopback-example-relation), the views directory is inside `server/views`. If you run `slc run` inside the `server` directory, the application works properly. If you run `slc run` from the project root, it fails because by default, Express looks for views in `./views` (but its really in `server/views`.

After speaking with @sam-github, it was suggested that `app.boot()` needs to determine the project root given its knowledge of the project layout.

**Comment by bajtos** [comment]
@superkhau Is this issue still relevant? 

Your `server/server.js` configures the views location to an absolute path (see below), that should have fixed the problem, right?

```
app.set('views', path.resolve(__dirname, 'views'));
```

**Comment by superkhau** [comment]
@bajtos It's not relevant since you do set the views dir as you've shown. However, I do feel we should at least set the view dir to `server/views` OOB. Two main benefits that I see:

1. Since we include `ejs` OOB, we can write a yeoman generator to set up server side templates on demand
  - slc loopback:server-template
    - `rm server/boot/root.js`
    - `mkdir server/views`
    - echo 'Hello world` > server/views/index.html`
    - Add static middleware (MW) in  `middleware.json` to point static `server/views`
    - Modify `server.js` or add another MW that simply does `app.set('view engine', 'ejs') - OR include this OOB
2. We don't have to explain to users why the default view dir is in './views` instead of `./server/views`

I actually want to do this for the users who DO NOT want to build SPAs. They can simply run the generator, get server templates working and focus on models, etc. A bonus is we would standardize how users set this up for basic usage.

Thoughts?

**Comment by bajtos** [comment]
> Add static middleware (MW) in middleware.json to point static server/views

That's not correct, you should not serve the views via static middleware. You should use [res.render()](http://expressjs.com/4x/api.html#res.render) instead.

Just saying :)

> I actually want to do this for the users who DO NOT want to build SPAs. They can simply run the generator, get server templates working and focus on models, etc. A bonus is we would standardize how users set this up for basic usage.

The current project template is called "API server", that's why it does not provide server-side templates not a static SPA client.

I am ok to add a new project template for building old-style static websites. However, you need more come up with a good convention for setting up server routes for that.

I am proposing to close this issue as "won't fix" and open a new issue in generator-loopback or loopback-workspace tracking your feature request.

Thoughts?

**Comment by bajtos** [comment]
> We don't have to explain to users why the default view dir is in `./views` instead of `./server/views`

I see why this can be confusing. How about implementing the following solution: when the `views` path is starting with `./` or `../`, we will resolve it relatively to the directory where the main app file is, i.e. value `./views` will be resolved as `{abs-path-to-your-project}/server/views`. Then we can change the API server template in loopback-workspace and set the `views` value in `server/config.json` to `./views`.

**Comment by superkhau** [comment]
>That's not correct, you should not serve the views via static middleware. You should use res.render() instead.

You are right. We should set static MW to `./client` and serve the server-side templates from `./server/views` (using `res.render` of course) is what I meant. ;)

>The current project template is called "API server", that's why it does not provide server-side templates not a static SPA client.

Makes sense. It's just part of two features I would like LoopBack to have at some point, which is:

1. Generator to set up basic SPA site (ie. remove `server/boot/root`, add entry to `middleware.json` files section to serve static assets from `./client`
2. Generator to set up non SPA old school site using server-side templates (ie. remove `server/boot/root`, `modify middlware.json`, set up proper views dir at `./server/views`, scaffold `./server/views/index.html`

This will help us set up all the boilerplate for new examples.

>I am proposing to close this issue as "won't fix" and open a new issue in generator-loopback or loopback-workspace tracking your feature request.

This sounds good. I think we should create two issues (one for each type of site mentioned above). We can continue the conversations other there instead.

**Comment by superkhau** [comment]
Closing as this is not high priority at all.
