### ISSUE TITLE
Do not cache content of config files in the compiler

### ISSUE THREAD

**Issue by coodoo** [strongloop/loopback-boot#48]
At line 54 of `compiler.js`

https://github.com/strongloop/loopback-boot/blob/51cf0052d07de5e1e46828707b152ffa934ef915/lib/compiler.js#L54

Is there any reason to delete `_meta` property from modelsConfig? This caused trouble for watching and rebuilding script for that 2nd time the script run, `_meta` was deleted and some model files won't be included in the final bundle.

**Comment by richardpringle** [comment]
@coodoo, is this safe to close?
