### ISSUE TITLE
Extend options arg to support custom model definitions

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-boot#49]
Extend the `options` argument of `boot`/`compile` to allow the developer to supply custom model definitions (to replace the result of `findModelDefinitions`). Together with the existing `options.models`, it will allow you to specify all model-related data and still use the benefits which loopback-boot provides (most notably loading models in order defined by inheritance, i.e. base models are loaded before models that are extending them).

```js
boot(app, {
  models: {
    Car: { dataSource: 'db' },
    // etc.
  },
  modelDefinitions: [
     {
       definition: {
         name: 'Car',
         properties: { /*...*/ }
       },
       sourceFile: 'path/to/car.js'
    },
    // etc.
  ]
});
```

This is a follow-up for #27.

**Comment by shlomiassaf** [comment]
@bajtos,

I sent PR for this enhancement, #96 
Could you please check?

Thanks.
