### ISSUE TITLE
Declarative definition of model property validations

### ISSUE THREAD

**Issue by cajoy** [strongloop/loopback-boot#62]
Loopback/Yo generator creates model with validations property:

```
{
  "name": "account",
  "options": {
    "mongodb": {
      "table": "account"
    },
  },
  "dataSource": "mongodb",
  "properties": {
    "name": {
      "type": "String"
    },
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": []
}
```

But I can't find any example or definition of it.

How to use validations?

**Comment by bajtos** [comment]
AFAICT, LoopBack does not support a declarative way of defining property validations, beyond the per-property attributes like "required" and "unique". The same applies to "methods", it's too not supported yet.
