### ISSUE TITLE
Multiple invocation of the same boot script

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-boot#64]
#31 introduced `options.bootScripts` that can be used to specify additional boot scripts to execute. The implementation uses a simple `concat`-based algorithm to build a list of all scripts to execute. As a result, it's possible to get the same boot script (exported function) executed twice.

Consider the following example:

```
// boot/step.js
console.log('step loaded');
module.exports = function(app) {
  console.log('step executed');
};

// app.js
boot(app, {
  appRootDir: __dirname,
  bootScripts: [ path.resolve(__dirname), 'boot', 'step.js' ]
});
```

Actual output:

```
step loaded
step executed
step executed
```

Expected output:

```
step loaded
step executed
```

**Comment by noderat** [comment]
At the bottom of the [documentation on boot scripts](https://docs.strongloop.com/display/public/LB/Defining+boot+scripts) it is still warning that boot scripts will be duplicated. Can the documentation be updated?

Also, is there a better resource for suggesting updates to the documentation or perhaps a way to do a pull request for documentation fixes?

**Comment by superkhau** [comment]
@noderat https://github.com/strongloop/loopback/wiki/Contributing-documentation
