### ISSUE TITLE
Compiler Glob Style File lookups

### ISSUE THREAD

**Issue by esatterwhite** [strongloop/loopback-boot#69]
It would be much cleaner and easier to maintain from a project standpoint, if the compiler could use glob patterns to locate files over hard coded paths and private filter functions.

rather than instead of 

``` js
"../common/models",
"../server/models",
"./models",
"../../../project/auth/models",
"../../../project/products/models"
```

it can just be

``` js
"node_modules/loopback/**/models/*.+(js|json)",
"../../../project/pluggables/**/models/*.+(js|json)"
```

This would reduce the amount of hand managed configuration. It also makes it easier to support pluggable pieces by convention in one's application.

**Comment by bajtos** [comment]
Thank you for a suggestion. One question comes to my mind: at the moment, the order of items defines the priority. In your example above, models defined in `../common/models` have higher priority than models defined in `./models`. Have you considered this aspect?

**Comment by esatterwhite** [comment]
That sounds like a sort & regex to re order the glob results                                                                                                                                                                                                                                                                           Sent from my BlackBerry 10.                                                                                                                                                                                                                                         From: Miroslav BajtošSent: Wednesday, February 4, 2015 9:32 AMTo: strongloop/loopback-bootReply To: strongloop/loopback-bootCc: esatterwhiteSubject: Re: [loopback-boot] Compiler Glob Style File lookups (#69)Thank you for a suggestion. One question comes to my mind: at the moment, the order of items defines the priority. In your example above, models defined in ../common/models have higher priority than models defined in ./models. Have you considered this aspect?

—Reply to this email directly or view it on GitHub.
