### ISSUE TITLE
Warn the user when a config file was not found, but overrides exist

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-boot#82]
See #71:

> A few weeks back I was reading loopback's confluence docs and came across the config page. I saw the alternative config options that loopback supports and I thought: "oh, so I could use a smarter config! Great I need that". so I went ahead, renamed config.json to config.local.js and started converting the code. Substituting json config with a js config was second nature because I've seen it in many projects including my own. I restarted the server and realized the config was not picked up. I went back to the docs page and still couldn't figure it out. It was only after reading the source code that I was able to understand the config requirements. it took a few hours overall as I couldn't immediately spot where configuration is processed.

We should detect such situation and print a warning.

Related: #80.

**Comment by superkhau** [comment]
Connect to #162
