### ISSUE TITLE
Config merge order

### ISSUE THREAD

**Issue by doublemarked** [strongloop/loopback-boot#84]
Hello!

As far as I can tell, loopback-boot is merging datasource configs in an order of ``env -> local -> master``, meaning that local config values get clobbered by environment-specific ones. This surprised me, as my understanding from the docs is that local config files are intended to be excluded from VCS and serve as a trump for local setup. I had intended to use this file to tweak a few values in the development environment datasource setup. 

Are my expectations off? I would have expected the merge to happen in the order ``local -> env -> master``, meaning that local datasource config trumps environment, with all of them overriding the general config.

**Comment by bajtos** [comment]
I see your point. It really depends on how you want to use env and local files, IMO both orders make sense.

>  I had intended to use this file to tweak a few values in the development environment datasource setup.

This is how I was envisioning the configuration:

 - development environment setup goes to the master config file
 - local (per-machine) tweaks in the development environment go to `.local.json` file

Can you use this approach? If not, can you please describe why it does not work for you?

It turns out that most people use `.local.js` to implement dynamic configuration on top of basic json-based stuff. In the light of that, it may be best to deprecate `.local` suffix and replace it with `.dynamic` called at before `.local`, and `.machine` called at the end:

    machine -> {env} -> local -> dynamic -> master

Thoughts?

See also #80.

**Comment by bajtos** [comment]
I see. When designing the config file layers, I did not take into account that per-environment config would have two parts - version-controlled settings and sensitive configuration not stored in version control. I was thought that all per-environment changes will stay in a single file. Mae culpa.

Before we go further down this route, have you considered using environment variables for values you don't want to store in version-controlled files? See #4 and http://12factor.net/config for more information about that approach.

**Comment by doublemarked** [comment]
I like this approach outlined in #4. The intention is that such values would be automatically merged into the config, yes? This approach would accommodate all the expectations I outlined above and remove the need for us to have 'dynamic' config files. 

That said - these env vars will still inevitably need to be stored in some file that is held outside of VC (like ``.env``). But regardless, the approach sounds pretty agreeable and would collapse a lot of the config file complexity we currently experience.

**Comment by bajtos** [comment]
> I like this approach outlined in #4. The intention is that such values would be automatically merged into the config, yes? 

Yes. The values from the environment take precedence over everything else.

> This approach would accommodate all the expectations I outlined above and remove the need for us to have 'dynamic' config files.

Can we close this issue then?

**Comment by doublemarked** [comment]
Yes, can close.

Is #4 on track for release at some point?

**Comment by bajtos** [comment]
>  Is #4 on track for release at some point?

Not in the near future. Would you mind contributing the feature yourself? I am happy to guide you along the way and help you to get the pull request into the state when it's good to be merged.

**Comment by doublemarked** [comment]
I would indeed enjoy working on this, though it won't be possible within the next couple weeks. I'll ping you when I have a chance to put some time into it.
